dt = 0.05
rocketexhaustmass = 30
rocketexhaustvelocity = 1000
fuelinmiss = 20
size = 2000
planetmass = size * 5000
ship_angular_rotational_velocity = 4
ship_angular_acceleration = 0.1
playeracceleration = 20
autosave = True
loadlatest = True
missiledisappeartime = 5
trailmaxlength = 100
zoom_value = 1